#!/usr/bin/env bash
# a script that configures a new ubuntu machine
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo mkdir -p /var/www/html
sudo chmod -R 755 /var/www
echo "Hello World!" > /var/www/html/index.nginx-debian.html;
SERVER_BLOCK=\
"server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;

        server_name _;
	location / {
		try_files \$uri \$uri/ =404;
	}
	if (\$request_filename ~ redirect_me){
		rewrite ^ https://github.com/holic65 permanent;
	}
}"
bash -c "echo -e '$SERVER_BLOCK' > /etc/nginx/sites-available/default"
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites/enabled/
sudo /etc/init.d/nginx restart
