#!/usr/bin/env bash
# a script that configures haproxy on server
sudo apt update
sudo apt install haproxy -y

initfile=/etc/default/haproxy
haconfig=/etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a "$initfile"

config=\
"

frontend manage_access
	bind *:80
	default_backend my_servers

backend my_servers
	balance roundrobin
	server 26582-web-01 54.236.28.84:80 check
	server 26582-web-02 100.27.12.84:80 check
"

echo "$config" | sudo tee -a "$haconfig"
sudo systemctl restart haproxy.service
