#!/usr/bin/env bash
# a script that configures haproxy on server
sudo apt update
sudo apt install haproxy -y

initfile=/etc/default/haproxy
haconfig=/etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a "$initfile"

config=\
"

frontend myfrontend
	bind *:80
	default_backend myservers
backend myservers
	balance roundrobin
	server web-01 54.85.93.141:80 check
	server web-02 34.201.165.179:80 check
"

echo "$config" | sudo tee -a "$haconfig"
sudo systemctl restart haproxy.service
