#!/usr/bin/env bash
# a bash scrip that debugs failed to connect error
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
