#!/usr/bin/env bash
# A script that creates a file
# it reads a statement when SIGTERM signal is passed
# it reads removes the file when SIGINT or SIGTERM is passed
# An infinite loop is created also
echo $$ > /var/run/myscript.pid
trap "echo I hate the kill command; rm /var/run/myscript.pid" SIGTERM
trap "Y U no love me?!" SIGINT
trap "rm /var/run/myscript.pid" SIGQUIT
while true
do
	echo "To infinity and beyond"
	sleep 2
done
