#!/usr/bin/env bash
# A script that starts close and restarts a script

command=$1

if [ "$command" == "start" ]
then
	./manage_my_process &
	echo $$ > /var/run/my_process.pid
	echo "manage_my_process started"

elif [ "$command" == "stop" ]
then
	kill "$(pgrep -f /manage_my_process)"
	rm /var/run/my_process.pid
	echo "manage_my_process stopped"

elif [ "$command" == "restart" ]
then
	kill "$(pgrep -f /manage_my_process)"
	rm /var/run/my_process.pid
	./manage_my_process &
	echo $$ > /var/run/my_process.pid
	echo "manage_my_process restarted"

else
	echo "Usage: manage_my_process {start|stop|restart}"
fi
